### ISSUE TITLE
Connector ignores clients of Categories

### ISSUE THREAD

**Issue by franzlst** [plentymarkets/plentymarkets-shopware-connector#101]
| Q                       | A
| ----------------------- | ---
| Bug?                    | yes
| Version                 | 2.0 latest

The plenty REST API for `/categories?with=clients` returns a list of clients, for which a category is active/assigned (the `clients` field of `entries`). This is currently ignored by the connector. This causes all existing and configured categories in plenty to be created in Shopware.

**Comment by jochenmanz** [comment]
Hallo Franz,

the bug should be fixed in my current development branch. Could you verify that?

Best regards,
Jochen

**Comment by jochenmanz** [comment]
verified with your installation. Thanks for your help franz :)
