### ISSUE TITLE
Error while synchronizing all products

### ISSUE THREAD

**Issue by franzlst** [plentymarkets/plentymarkets-shopware-connector#112]
The following exception is raised:
`throw new \Exception('shippingProfile is not a allowed attribute key');`
(inHandleProductCommandHandler.php)
I added some debug output in the  `if (!empty($shopAttribute)) {` branch, here is the log:
https://pastebin.com/MA62Gean
Appears only for article id1006

**Comment by jochenmanz** [comment]
You got the first product with multiple shipping profiles, i've implemented a fix for that.

**Comment by jochenmanz** [comment]
verified the fix on your installation. Thanks for your help Franz 👍
