### ISSUE TITLE
Customer newsletter is not transferred

### ISSUE THREAD

**Issue by jochenmanz** [plentymarkets/plentymarkets-shopware-connector#138]
| Q                       | A
| ----------------------- | ---
| Bug?                    |yes
| New Feature?            | no
| Version                 | 2.0

#### Actual Behavior

if a customer has accepted the newsletter checkbox during checkout, it is not transferred.

#### Expected Behavior

field is transferred

**Comment by franzlst** [comment]
I would like to reopen this issue. Newsletter allowances are still not (correctly) transferred. I checked for several customers that are listed in the newsletter manager of Shopware: None of them had the "Newsletter" checkbox ticked in plenty.
