### ISSUE TITLE
Payment status PayPal Starter

### ISSUE THREAD

**Issue by franzlst** [plentymarkets/plentymarkets-shopware-connector#173]
| Q                       | A
| ----------------------- | ---
| issue or Enhancement    | issue
| Version                 | 2.0.3

I have the PayPal plugin installed in Shopware, the payment method 'paypal' is mapped to 'PayPal' in plenty. For some orders using PayPal, the payment method in plenty is set to "PayPal Starter". For these orders, the payment is not set (no payment is assigned), so in plenty, it says the order hasn't been paid (although in SW the payment status is completely paid).

For other orders using PayPal, the payment method in plenty is set to "PayPal Express". In these cases, the payment is correctly assigned.

**Comment by Pfabeck** [comment]
Hello Franzist,
you probably mapped the wrong plentymarkets payment id (check in DB).

best regards Patryk
