### ISSUE TITLE
Properties (merkmale) are only transferred only when the property is searchable

### ISSUE THREAD

**Issue by smxvh** [plentymarkets/plentymarkets-shopware-connector#286]
Hi all,
PlentyConnector/Adapter/PlentymarketsAdapter/ResponseParser/Product/ProductResponseParser.php on line #477 is a check, if the property is searchable. 

`
if (!$property['property']['isSearchable']) {
    continue;
}
`
Our opinion is, that this is not correct.

**Comment by marcmanusch** [comment]
Das ist so gewollt und notwendig. Das Merkmal wird nur übertragen wenn es durchsuchbar ist, dadurch kann man steuern ob die Merkmale zu Shopware sollen oder nicht.

**Comment by jochenmanz** [comment]
Muss ich leider als wontfix markieren. Wie @marcmanusch schon richtigerweise angemerkt hat, ist das Verhalten aktuell so gewollt. Du kannste jedoch über ein Plugin das ganze Anpassen und an deine Anforderungen angleichen :)
