### ISSUE TITLE
Error synching the Products

### ISSUE THREAD

**Issue by Kwazi083** [plentymarkets/plentymarkets-shopware-connector#310]
![image](https://user-images.githubusercontent.com/39833616/40845879-3d0bde80-65b8-11e8-8279-fd08d0eb625c.png)

Hi,
 I'm getting this error messages when I run my product synch. Please help me understand it and resolve it.

Regards,
Kwazi

**Comment by Kwazi083** [comment]
Hi,

How do I map the item master in Plentymarkets to shopware item master so I can be able to populate the correct fields with the correct information?

Regards,
Kwazi

**Comment by Pfabeck** [comment]
Hi,
Support only via Plenty Forum.

Regards Patryk
