### ISSUE TITLE
Plugin get error over the 200Req/min

### ISSUE THREAD

**Issue by sorinpopescu** [plentymarkets/plentymarkets-shopware-connector#325]
| issue
| Version latest

#### Actual Behavior

Error of Requests exceded

#### Expected Behavior

To work!

#### Steps to Reproduce

run the console process

**Comment by lacodimizer** [comment]
You have to upgrade the rest api limit by plentymarkets. (https://forum.plentymarkets.com/t/sammelthread-plentymarkets-api-rest-limit-erhoehung/82693/244)

**Comment by jochenmanz** [comment]
as @lacodimizer pointed out, the rest limit
