### ISSUE TITLE
onOrderModelPostPersist event registration behaviour

### ISSUE THREAD

**Issue by jochenmanz** [plentymarkets/plentymarkets-shopware-connector#39]
Hallo,

when working on an issue for one of our customers, i found out that the following event is not registered persistently on all our installations. I would suspect that some had older Versions installed as the Event is registered inside the update function but commented out inside the install function.

If the subscribeEvent was commented out by mistake, i can provide a PR.

Best regards,
Jochen

**Comment by ioanamoldovan** [comment]
Hi,
the onOrderModelPostPersist event is no longer used for Shopware Connector versions higher than 1.7. This ensures compatibility with Shopware version 5. Therefore, this event is only created for Shopware Connector versions 1.7 and lower, which are still compatible with Shopware version 4. 
The subscribeEvent was not inadvertently commented out.

We hope we could help you with this issue. Thank you.

Best regards,
Ioana Moldovan

**Comment by jochenmanz** [comment]
Hallo,

the Problem persists that you cannot create orders from aborted carts. The plenty_orders entry is then missing.

Best regards,
Jochen

**Comment by ioanamoldovan** [comment]
Hi,
can you tell me please the shopware and shopware connector versions, where this problem occurs?

Best regards,
Ioana

**Comment by arvatis** [comment]
Hi,

Shopware: 5.0.2
Connector: 1.7.4

Best regards,
Jochen

**Comment by ioanamoldovan** [comment]
Hi,

ich habe Rücksprache gehalten und wir werden den Erreignis onOrderModelPostPersist auch beim Installieren des Connectors wieder reinnehmen. Ich danke dir für den Hinweis.

Gruß
Ioana

**Comment by arvatis** [comment]
Hallo Ioana,

please also add the event to the next version's update method in case there are installations without the event at all. Our Customer for example was missing that event completly. Events can savely be registered more then once.

Best regards,
Jochen
