### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sorinpopescu** [plentymarkets/plentymarkets-shopware-connector#391]
constant(): Couldn't find constant SystemConnector\TransferObject\Category\Category::TYPE

| Q                       | A
| ----------------------- | ---
| issue or Enhancement    | issue|Enhancement
| Version                 | Specific version or SHA of a commit

#### Actual Behavior

What is the actual behavior?

#### Expected Behavior

What is the behavior you expect?

#### Steps to Reproduce

What are the steps to reproduce this bug? Please add code examples,
screenshots or links to GitHub repositories that reproduce the problem.

#### Possible Solutions

If you have already ideas how to solve the issue, add them here.
(remove this section if not needed)

**Comment by Pfabeck** [comment]
What are the steps to reproduce this bug? Please add code examples,
screenshots or links to GitHub repositories that reproduce the problem.
