### ISSUE TITLE
Export/Import of PlentyMarkets name2 & name3

### ISSUE THREAD

**Issue by florianliebig** [plentymarkets/plentymarkets-shopware-connector#412]
Enhancement

#### Actual Behavior

What is the actual behavior?

PlentyMarkets textfields name2 & name3 are not imported into shopware

#### Expected Behavior

PlentyMarkets textfields name2 & name3 are imported into shopware

#### Steps to Reproduce

-

#### Possible Solutions

similar to function getTechnicalDataAsAttribute in PlentymarketsAdapter\ResponseParser\Product\ ProductResponseParser name2 and name3 could be added as additional attributes in shopware

**Comment by jochenmanz** [comment]
@florianliebig i have added the two fields as attributes in my current pr: https://github.com/plentymarkets/plentymarkets-shopware-connector/pull/413/files#diff-b4837330346b6933debe587aa9284409 thanks for your suggestion :)
