### ISSUE TITLE
Price sync

### ISSUE THREAD

**Issue by sorinpopescu** [plentymarkets/plentymarkets-shopware-connector#416]
SPW: 5.5.4
PMC: Latest version

I cannot get the prices. I have try everything:
- mapping is done ok
- shop it's assigned ok
- groups are setup
In PM - the prices are ok to go.

On product all the informations comes ok, stock, descriptions, etc except prices.

What should I do?

**Comment by jochenmanz** [comment]
@sorinpopescu if you can post that question on the plentymarkets support forum (https://forum.plentymarkets.com/c/shopware-connector) In short the price sync collects all prices that are valid (by shop and origin if configured), sorts them by their starting amount and groups the prices with the RLP. The least possible starting amount is 1. The easiest way to configure that feature ist by doing the following:

- disable all other prices
- add a price for the shopware shop starting at 1
- add a RLP for the shopware shop starting at 1
