### ISSUE TITLE
Orders sync

### ISSUE THREAD

**Issue by sorinpopescu** [plentymarkets/plentymarkets-shopware-connector#417]
SPW: 5.5.4
PMC: latest version

Once you place an order on SPW, when crons run, the order goes ok to PM.
On PM side, if you change the order, like change QTY, alter price or add a new item to the order, that is not sync back to SPW. Is there an issue? Or?

Thanks

**Comment by jochenmanz** [comment]
@sorinpopescu currently only the order status, payment status and tracking informations are synced back to shopware. But if you like you could start working on that feature, that would benefit us all :)
