### ISSUE TITLE
Cronjob error because column end is NULL

### ISSUE THREAD

**Issue by michael-rusch** [plentymarkets/plentymarkets-shopware-connector#419]
Hello,

#### Actual Behavior
I noticed that the cron jobs change the status to inactive if the database column end is NULL. The database column end should not have the value NULL, because in some cases the cron job aborts. If the option "Disable on errors" is activated but no e-mail address is stored, the administrator will not be informed.

#### Expected Behavior
When executing the conjob, you should first check whether the column end has the value NULL or not.

#### Steps to Reproduce
Unknown

#### Possible Solutions
Whether the cron job is executed correctly or it is aborted due to an error, the cron job in the database should always be saved correctly.

A semantic example:
try {
   #run cron
} catch {
   #catch errors
} finally {
    #save cronjob in database
}

**Comment by jochenmanz** [comment]
@michael-rusch the installer sets the end column to the date and time of the installation. After that its up to shopware how to handle the actual cronjob. This looks like a shopware bug to me. Which Version of shopware are you using?

**Comment by michael-rusch** [comment]
Shopware 5.4.6, Connector 4.6.0

**Comment by Pfabeck** [comment]
Hey Michael,
ich close das hier.
