### ISSUE TITLE
Fatal error on sync

### ISSUE THREAD

**Issue by sorinpopescu** [plentymarkets/plentymarkets-shopware-connector#420]
SPW: 5.5.4
PLMC: latest version

We have run the sync command from SPW to PLM and now it's stay for days, transfering more than 4G and 49% it fails with the fatal error. (attached)

![image](https://user-images.githubusercontent.com/2951110/48333707-139be480-e661-11e8-960d-a96cf61788e4.png)

**Comment by jochenmanz** [comment]
@sorinpopescu you are using a PHP Version lower then php7.0. Starting with php7.0 all exceptions use the base class Throwable and the error above cant happen.
