### ISSUE TITLE
[Bug] eMail with special chars will not be accepted

### ISSUE THREAD

**Issue by bestit-baumann** [plentymarkets/plentymarkets-shopware-connector#44]
Hi there,
in some special cases, customers will used special chars like "+" in their eMail adress.

So in this case, the customer tries so add a GMail feature to "sort into Folder" like this:
my.name+plenty@gmail.com > This mail will direct sorted to Folder "plenty" in inbox.

`<Email xsi:type="xsd:string">my.name+plenty@gmail.com</Email>`

```
<ResponseMessages xsi:type="ns1:ArrayOfPlentysoapresponsemessage">
<item xsi:type="ns1:PlentySoapResponseMessage">
<Code xsi:type="xsd:int">800</Code>
<IdentificationKey xsi:nil="true"/>
<IdentificationValue xsi:nil="true"/>
<SuccessMessages xsi:nil="true"/>
<ErrorMessages xsi:type="ns1:ArrayOfPlentysoapresponsesubmessage">
<item xsi:type="ns1:PlentySoapResponseSubMessage">
<Value xsi:type="xsd:string">Invalid parameter</Value>
<Key xsi:type="xsd:string">Email</Key>
</item>
</ErrorMessages>
```

**Comment by bestit-baumann** [comment]
@jochenmanz » Maybe you link the forum at readme.md ?
https://github.com/plentymarkets/plentymarkets-shopware-connector

**Comment by jochenmanz** [comment]
@bestit-baumann 

Good catch, i will update the readme with my next changes and create a forum post on your behalve. For the meantime, would you be interessted in creating a PR where we strip "something+" from the mail addresses? 

Best regards,
Jochen
