### ISSUE TITLE
 cURL error 3: Bad URL, colon is first character 

### ISSUE THREAD

**Issue by doctor-damager** [plentymarkets/plentymarkets-shopware-connector#440]
#### Actual Behavior

Mapping in backend and ssh not possible

#### Errors

Notice: Undefined index: scheme in /home/tweeto46/public_html/custom/plugins/PlentyConnector/Adapter/PlentymarketsAdapter/Client/Client.php on line 277

Notice: Undefined index: host in /home/tweeto46/public_html/custom/plugins/PlentyConnector/Adapter/PlentymarketsAdapter/Client/Client.php on line 277

Notice: Undefined index: scheme in /home/tweeto46/public_html/custom/plugins/PlentyConnector/Adapter/PlentymarketsAdapter/Client/Client.php on line 277

Notice: Undefined index: host in /home/tweeto46/public_html/custom/plugins/PlentyConnector/Adapter/PlentymarketsAdapter/Client/Client.php on line 277

Notice: Undefined index: scheme in /home/tweeto46/public_html/custom/plugins/PlentyConnector/Adapter/PlentymarketsAdapter/Client/Client.php on line 277

Notice: Undefined index: host in /home/tweeto46/public_html/custom/plugins/PlentyConnector/Adapter/PlentymarketsAdapter/Client/Client.php on line 277

Notice: Undefined index: scheme in /home/tweeto46/public_html/custom/plugins/PlentyConnector/Adapter/PlentymarketsAdapter/Client/Client.php on line 277

Notice: Undefined index: host in /home/tweeto46/public_html/custom/plugins/PlentyConnector/Adapter/PlentymarketsAdapter/Client/Client.php on line 277
[2018-12-25 15:20:41] plentyconnector.ERROR: cURL error 3: Bad URL, colon is first character  

#### Steps to Reproduce

 php bin/console plentyconnector:mapping

**Comment by jochenmanz** [comment]
your api url seems wrong, please use something like https://your-plenty-domain.de
