### ISSUE TITLE
add to documentation, how to change field mapping

### ISSUE THREAD

**Issue by Kipperlenny** [plentymarkets/plentymarkets-shopware-connector#493]
| Q                       | A
| ----------------------- | ---
| issue or Enhancement    | Enhancement    
| Version                 | 5.1.1

#### Actual Behavior

Herstellernummer is not the plenty manufactorer number.

#### Expected Behavior

client expects to export the Varianten Nr. to the Herstellernummer 

![image](https://user-images.githubusercontent.com/563328/59517513-0e876800-8ec4-11e9-9f00-d1442578f93e.png)

#### Possible Solutions

This is not included in the Connector Mapping in Shopware Settings. Please add to the documentation, where to change the mapping of these article fields.

**Comment by Pfabeck** [comment]
Moin Lennart,

für die Herstellernummer wird aus plentymarkets das Model Feld bezogen (siehe Doku):
![Bildschirmfoto 2019-10-28 um 09 57 40](https://user-images.githubusercontent.com/12063453/67665185-7fa65400-f969-11e9-8af7-88a65ef806b4.jpg)

Du kannst das mapping aber per dependency injection/decorator pattern anpassen:
Adapter/PlentymarketsAdapter/ResponseParser/Product/Variation/VariationResponseParser.php per 


Beste Grüße
Patryk
