### ISSUE TITLE
Error when transferring an Order

### ISSUE THREAD

**Issue by bvogel** [plentymarkets/plentymarkets-shopware-connector#494]
| Q                       | A
| ----------------------- | ---
| issue or Enhancement    | issue
| Version                 | fa137013d71d36ea270c378adadbea00ce57d275

#### Actual Behavior

What is the actual behavior?
On synchronizing an Order I get the following error in the log:
```
 125/500 [▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░]  25% 5 mins/20 mins 96.0 MiB[2019-06-19 11:20:59] plentyconnector.ERROR: Command failed: TransferObjectCommand {"adapterName":"PlentymarketsAdapter","objectType":"Order","commandType":"handle","priority":90,"payload":"115b3aff-0155-4b8f-b02f-bc94f982899f","exception":"[object] (RuntimeException(code: 0): client error at /var/www/clients/client1/web13/web/custom/plugins/PlentyConnector/Adapter/PlentymarketsAdapter/Client/Client.php:223)"}
```
Still the order is transferred apparently ok.

#### Expected Behavior

What is the behavior you expect?
No error

#### Steps to Reproduce

What are the steps to reproduce this bug? Please add code examples,
screenshots or links to GitHub repositories that reproduce the problem.
Transfer an order from SW to PM

**Comment by Pfabeck** [comment]
Hi,

tritt das Problem bei jeder Übertragung auf?

Beste Grüße
Patryk

**Comment by ArvatisJohannes** [comment]
Hallo @bvogel ,

mit version 5.2.1 wurde ein erweitertes Logging implementiert, welches diese Client Error Probleme etwas genauer ausgeben soll. Wahrscheinlich gibt es hier, wie wir bereits bei Artikeln erfahren mussten, Probleme bzw eine 404 response in den REST Routen von Plenty.

Diese müssten dann in Kooperation mit dem PlentyREST/Cloud Team besser debuggt werden.

Tritt der Fehler bei eurem System noch öfters auf?
Gab es dabei evtl auch schonmal das Phänomen, dass Orders doppelt angelegt wurden?

Mit freundlichen Grüßen,
Johannes Griebel
