### ISSUE TITLE
shouldn't be float

### ISSUE THREAD

**Issue by ArvatisJohannes** [plentymarkets/plentymarkets-shopware-connector#508]
https://github.com/plentymarkets/plentymarkets-shopware-connector/blob/abddbc3a899318e570acb540489110c343a024ca/Adapter/ShopwareAdapter/ResponseParser/OrderItem/OrderItemResponseParser.php#L88

tested with shopware 5.5.10
![Screen Shot 2019-08-16 at 17 07 08](https://user-images.githubusercontent.com/34513672/63177494-4dfb3d80-c048-11e9-81d2-f38a22d83536.png)

**Comment by kayaArvatis** [comment]
it should be $taxModel = $this->taxRepository->findOneBy(['tax' => (float)$entry['taxRate']]);

**Comment by ArvatisJohannes** [comment]
fixed with recent pullrequest https://github.com/plentymarkets/plentymarkets-shopware-connector/pull/510
