### ISSUE TITLE
The license mananger is not installed.

### ISSUE THREAD

**Issue by css-umsetzung** [plentymarkets/plentymarkets-shopware-connector#51]
in dieser Datei  plentymarkets-shopware-connector/Components/Utils/PlentymarketsStatus.php
setzt Ihr in Zeile 233 eine Variable die ihr dann auf true/false prüft

$ozymandias = isset($_ENV['ozymandias']) || (isset($_SERVER['QUERY_STRING']) && $_SERVER['QUERY_STRING'] == 'ozymandias');

wir haben den aktuellen  Licence-manager installiert in einer Shopware 5.x Version, bei uns ist diese Variable immer false. ? 

und wir bekommen dadurch die Meldung aus Zeile 255

**Comment by jochenmanz** [comment]
Hi,

the licence manager requirement will be dropped in the next major release. For now you can set the variable $ozymandias to true if you need to skip the check.

Best regards,
Jochen Manz
