### ISSUE TITLE
Standard Sprache des Connector

### ISSUE THREAD

**Issue by iLuHa91** [plentymarkets/plentymarkets-shopware-connector#52]
Die Standard-Sprache die sich der Connector aus Plenty zieht, ist Hard-Coded hinterlegt.
Hat man z.B. einen französischen Shopware Shops und pflegt seine Daten in Plenty (Standard-Sprache: französisch), versucht er sich alle Basis-Informationen aus der deutschen Sprache zu ziehen.

Hier sollte man an den Stellen, an denen Hard-Coded Lang='de' hinterlegt ist evtl. die Sprache des Shopware Shops auslesen um hier ein wenig flexibler zu sein.

**Comment by jochenmanz** [comment]
Hi,

there are 2 PR's open regarding the default language of the connector. If everything is fine they will be included in the next major version. It would be great if you ca check them out and see if they fit your needs and if they work still as expected.

Best regards,
Jochen Manz

**Comment by iLuHa91** [comment]
Mir ging es hier vor allem um den Hauptshop.
Kleines Beispiel:

Wir haben einen Shopware Shop, bei diesem gibt es aber gar keine deutsche Sprache, denn es ist ein französischer Shop. Somit ist die Lokalisierung des Shops ebenfalls auf französisch gestellt.

Der Connector zieht mir jedoch sowohl die Kategorien, als auch die Artikelbeschreibungen usw. aus der deutschen Sprache.

Der Connector sollte beim Synchronisieren auch die Lokalisierung des Hauptshops beachten, dies tut er  aber aktuell scheinbar nur bei Sprachshops.
