### ISSUE TITLE
Connector übernimmt falsche Sprache

### ISSUE THREAD

**Issue by franzlst** [plentymarkets/plentymarkets-shopware-connector#79]
| Q                       | A
| ----------------------- | ---
| Bug?                    | yes
| Version                 | 2.0 RC

Ein Artikel (ID 340) hat bei mir Texte in zwei Sprachen, deutsch und französisch. Das Mapping in Shopware ist korrekt eingestellt. Bei der Synchronisation übernimmt der Connector jedoch die französische Sprache, statt der deutschen.

**Comment by jochenmanz** [comment]
Hallo Franz,

i could reproduce the issue and fixed it in my current development branch. Thanks for your help 👍 

Best regards
Jochen
